= jdeps-gradle-plugin
:linkattrs:
:project-owner:   kordamp
:project-repo:    maven
:project-name:    jdeps-gradle-plugin
:project-group:   org.kordamp.gradle
:project-version: 0.8.0

image:http://img.shields.io/travis/{project-owner}/{project-name}/master.svg["Build Status (travis)", link="https://travis-ci.org/{project-owner}/{project-name}"]
image:http://img.shields.io/badge/license-ASL2-blue.svg["ASL2 Licensed", link="http://opensource.org/licenses/ASL2"]
image:https://api.bintray.com/packages/{project-owner}/{project-repo}/{project-name}/images/download.svg[link="https://bintray.com/{project-owner}/{project-repo}/{project-name}/_latestVersion"]
image:https://img.shields.io/badge/donations-Patreon-orange.svg[link="https://www.patreon.com/user?u=6609318"]


---

Runs the `jdeps` command on the project's output and all of its dependencies.

== Usage

Option #1
[source,groovy]
[subs="attributes"]
----
buildscript {
    repositories {
        jcenter()
        gradlePluginPortal()
    }
    dependencies {
        classpath '{project-group}:{project-name}:{project-version}'
    }
}
apply plugin: '{project-group}.jdeps'
----

Option #2
[source,groovy]
[subs="attributes"]
----
plugins {
    id '{project-group}.jdeps' version '{project-version}'
}
----

This will add a `jdepsReport` task to your build, which will analyze the `main` sourceSets and all dependencies found in the
`runtime` configuration.

== Configuration
=== Plugin configuration

The following properties can be specified in the `jdeps` task configuration

|===
| Name             | Type                 | Default Value
| verbose          | boolean              | false
| summary          | boolean              | false
| profile          | boolean              | false
| recursive        | boolean              | false
| jdkinternals     | boolean              | true
| consoleOutput    | boolean              | true
| reportsDir       | File                 | "${buildDir}/reports/jdeps"
| configurations   | List<String>         | ['runtime']
| classpaths       | List<String>         | ['compileClasspath', 'runtimeClasspath', 'testCompileClasspath', 'testRuntimeClasspath']
| sourceSets       | List<String>         | ['main']
| multiRelease     | Integer              |
| multiReleaseJars | Map<String, Integer> | [:]
| include          | String               | null
|===

You may configure multiple sourceSets and configurations, which will be evaluated in a single report. The following snippet
shows how this plugin can be configured to run `jdeps` on production and test sources

[source]
----
jdepsReport {
    sourceSets = ['main', 'test']
    configurations = ['testRuntime']
}
----

=== MultiRelease JAR support

You may configure a version for the `multiRelease` property in which case this setting will be applied `--multi-release &lt;version&gt;`
an all dependencies. If you need to check different releases per dependency then use the `MultiReleaseJars` property
instead, for example

[source]
----
jdepsReport {
    multiReleaseJars = [
        'foo-1.0.0': 11,  // matches full name
        'bar.*': 12       // matches all files with 'bar' as prefix
    ]
}
----

=== MonkeyPatching the module

There are times when explicit modular settings may be needed to generate a jdeps report.
You have the option to specify these settings using a moduleOptions extension on the `jdepsReport task,
for example

[source]
----
jdepsReport {
    moduleOptions {
        addModules = ['com.acme.foo']
    }
}
----

=== Restricting jdeps scan to specific classes

Using the 'include' option with a regex will ensure that only classes of your choosing are scanned.
This is particularly useful for avoiding Java 9+ jdk.unsupported errors for dependency classes that are
beyond your control and as yet do not have a release that complies with the Java 9+ standard.

[source]
----
jdepsReport {
    include = 'com.myorg.*|org.anotherorg.*'
}
----
